products = [
    {
        '_id': '1',
        'name': 'Cheesy Ham Sandwich',
        'image': '/images/sandwich1.jpg',
        'description': 'Delicious ham and cheese sandwich',
        'category': 'Sandwich',
        'price': 140,
        'countInStock': 10,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '2',
        'name': 'Cheesy Meat Sandwich',
        'image': '/images/sandwich2.jpg',
        'description': 'Tasty meat and cheese sandwich',
        'category': 'Sandwich',
        'price': 140,
        'countInStock': 7,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '3',
        'name': 'Double Cheese Chicken Fingers',
        'image': '/images/chicken1.jpg',
        'description': 'Crispy chicken fingers with double cheese',
        'category': 'Chicken Fingers',
        'price': 160,
        'countInStock': 5,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '4',
        'name': 'Glazed Teriyaki Chicken Fingers',
        'image': '/images/chicken2.jpg',
        'description': 'Sweet teriyaki glazed chicken fingers',
        'category': 'Chicken Fingers',
        'price': 160,
        'countInStock': 11,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '5',
        'name': 'Caramel Macchiato',
        'image': '/images/coffee1.jpg',
        'description': 'Espresso, caramel, milk',
        'category': 'Signature',
        'price': 145,
        'countInStock': 20,
        'rating': 0,
        'numReviews': 0,
    },
    {
        '_id': '6',
        'name': 'Spanish Latte',
        'image': '/images/coffee2.jpg',
        'description': 'Espresso, condensed milk, milk',
        'category': 'Signature',
        'price': 155,
        'countInStock': 15,
        'rating': 0,
        'numReviews': 0,
    },
]
